name: CI/CD Pipeline - Train & Build Docker

on:
  push:
    paths:
      - 'MLProject/**' 

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install MLflow & Conda
      run: |
        pip install "mlflow==2.22.0" dagshub boto3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Retrain Model with MLflow Project
      id: training
      run: |
        mlflow run MLProject/ --experiment-name "CreditCard_Fraud_Detection_Production"
        
        PYTHON_EXE="${{ steps.setup-python.outputs.python-path }}"
        
        LATEST_RUN_ID=$($PYTHON_EXE -c "
        import mlflow
        client = mlflow.tracking.MlflowClient()
        try:
            exp = client.get_experiment_by_name('CreditCard_Fraud_Detection_Production')
            runs = client.search_runs(exp.experiment_id, order_by=['start_time DESC'], max_results=1)
            print(runs[0].info.run_id)
        except Exception as e:
            print(f'Error: {e}')
            import sys; sys.exit(1)
        ")
        
        if [ -z "$LATEST_RUN_ID" ]; then
          echo "ERROR: Run ID tidak ditemukan!"
          exit 1
        fi

        echo "Latest Run ID ditemukan: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      env:
        RUN_ID: ${{ steps.training.outputs.run_id }}
        DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/fraud-detection-model
      run: |
        echo "Building Docker Image for Run ID: $RUN_ID"
        
        sleep 60
        
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "$DOCKER_REPO:latest" \
          --enable-mlserver
        
        docker push "$DOCKER_REPO:latest"
        echo "Docker Image Pushed Successfully!"
