name: CI/CD Pipeline - Train & Build Docker

on:
  push:
    paths:
      - 'MLProject/**' 

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install MLflow & Conda
      run: |
        pip install "mlflow==2.22.0" dagshub boto3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Retrain Model with MLflow Project
      id: training
      run: |
        mlflow run MLProject/ --experiment-name "CreditCard_Fraud_Detection_Production"
        EXP_ID=$(mlflow experiments get -n "CreditCard_Fraud_Detection_Production" | grep "Experiment ID" | awk '{print $3}')
        LATEST_RUN_ID=$(mlflow runs list --experiment-id $EXP_ID | head -n 3 | tail -n 1 | awk '{print $1}')
        
        echo "Latest Run ID: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      env:
        RUN_ID: ${{ steps.training.outputs.run_id }}
        DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/fraud-detection-model
      run: |
        echo "Building Docker Image for Run ID: $RUN_ID"
        sleep 60
        
        # Build Docker Image tetap menggunakan mlflow models build-docker
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "$DOCKER_REPO:latest" \
          --enable-mlserver
        
        docker push "$DOCKER_REPO:latest"
        echo "Docker Image Pushed Successfully!"
